version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresql
      POSTGRES_DB: users

  # Mosca is a simple MQTT Broker
  # In OpenShift/Production we would use the Red Hat AMQ broker
  mosca:
    image: matteocollina/mosca
    ports:
      - "1883:1883" # MQTT
      - "80:80" # web interface